DROP TABLE IF EXISTS public.exam_room;
DROP TABLE IF EXISTS public.exam;
DROP TABLE IF EXISTS public.room;
DROP TABLE IF EXISTS public.body_part;

CREATE TABLE public.body_part
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    CONSTRAINT uq_body_part_name UNIQUE (name)
);

CREATE TABLE public.room
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    CONSTRAINT uq_room_name UNIQUE (name)
);

CREATE TABLE public.exam
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codice_ministeriale varchar(10) NOT NULL,
    codice_interno varchar(10) NOT NULL,
    descrizione_esame varchar(100) NOT NULL,
    body_part_id integer NOT NULL,
    CONSTRAINT fk_exam_body_part FOREIGN KEY (body_part_id) REFERENCES public.body_part(id),
    CONSTRAINT uq_exam_codice_ministeriale UNIQUE (codice_ministeriale),
    CONSTRAINT uq_exam_codice_interno UNIQUE (codice_interno)
);

CREATE TABLE public.exam_room
(
    exam_id integer NOT NULL,
    room_id integer NOT NULL,
    CONSTRAINT pk_exam_room PRIMARY KEY (exam_id, room_id),
    CONSTRAINT fk_exam_room_exam FOREIGN KEY (exam_id) REFERENCES public.exam(id),
    CONSTRAINT fk_exam_room_room FOREIGN KEY (room_id) REFERENCES public.room(id)
);
